In [1]:
import numpy as np

In [3]:
a = np.arange(16).reshape(4, 4)

In [4]:
a[:,[1,2]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [ ]:
np.ix_((0,1),(2,3))

(array([[0],
        [1]]),
 array([[2, 3]]))

In [8]:
xx=np.arange(27).reshape(3,3,3)

xx[[0,1],:,[0]]

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [13]:
xx

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [15, 16, 17]])